# Generated by Django 4.2 on 2023-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0003_alter_task_assignee_alter_task_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(default='label', to='labels.label'),
        ),
    ]
